#!/bin/bash

cd samplebins
wget http://andrewdutcher.com/helium/trafman -O ctf_arm
wget http://shell-storm.org/repo/CTF/CodeGate-2014-Juinor-Quals/nuclear/nuclear -O ctf_x86
wget http://shell-storm.org/repo/CTF/GITS-2013/Pwnable/Shiftd-100/shiftd-3a9c2a55e77d1467ee46dfb931170c737d24f310 -O ctf_amd64
wget http://andrewdutcher.com/helium/deepblue -O ctf_ppc

gcc test_arrays.c -o test_arrays_native
gcc test_arrays.c -m32 -o test_arrays_native32
gcc nested_loop.c -o nested_loop_native
gcc nested_loop.c -m32 -o nested_loop_native32
gcc test_division.c -o test_division_native
gcc test_division.c -m32 -o test_division_native32

# if the latter compiled but they're the exact same, remove the latter
[ -f test_arrays_native32 ] && [ -f test_arrays_native ] && diff test_arrays_native32 test_arrays_native >/dev/null && rm test_arrays_native32
[ -f nested_loop_native32 ] && [ -f nested_loop_native ] && diff nested_loop_native32 nested_loop_native >/dev/null && rm nested_loop_native32
[ -f test_division_native32 ] && [ -f test_division_native ] && diff test_division_native32 test_division_native >/dev/null && rm test_division_native32
